UserDB Class Reference
Represents a User's database.
#include <UserDB.h>
Public Member Functions
UserDB ()
Default constructor for the UserDB class.
void showAll ()
Displays information about all employees in the database.
void showByPerm (int permission)
Displays information about employees with a specific permission level.
void addUser (Employee *employee)
Adds a new employee to the database.
void delUser (int index)
Deletes an employee from the database.
int saveEmployees ()
Saves all employees to a file.
void loadEmployees ()
Loads employees from a file.
bool nifExists (int nif)
Checks if an employee with the given NIF exists in the database.
bool idExists (int id)
Checks if an employee with the given ID exists in the database.
~UserDB ()
std::set< Employee *, EmployeeNifCompare > getEmployees ()
Private Attributes
std::set< Employee *, EmployeeNifCompare > employees_
int num_employees_
Detailed Description
Represents a User's database.
This class is a container for the users. It is a set of employees and it is used to manage them.
Definition at line 34 of file UserDB.h.
Constructor & Destructor Documentation
UserDB()
UserDB::UserDB ()
Default constructor for the UserDB class.
Definition at line 64 of file UserDB.cpp.
               {
  this->num_employees_ = 0;
  this->loadEmployees();
}
References loadEmployees(), and num_employees_.
 UserDB()
UserDB::~UserDB ()
Definition at line 130 of file UserDB.cpp.
               {
  for (const auto& employee: employees_){
    delete employee;
  }
  employees_.clear();
}
References employees_.
Member Function Documentation
addUser()
void UserDB::addUser (Employee * employee)
Adds a new employee to the database.
Parameters
employee Pointer to the Employee object to be added.
Definition at line 70 of file UserDB.cpp.
                                 {
  std::cout << "Adding user..." << std::endl;
  employees_.insert(employee);
  num_employees_++;
}
References employees_, and num_employees_.
Referenced by DashBoard::addUser().
delUser()
void UserDB::delUser (int index)
Deletes an employee from the database.
Parameters
index The index of the employee to be deleted.
Definition at line 97 of file UserDB.cpp.
                        {
  std::cout << "Deleting user..." << std::endl;
  auto usertodel = employees_.begin();
  std::advance(usertodel, index);
  employees_.erase(usertodel);
  delete *usertodel;
  num_employees_--;
}
References employees_, and num_employees_.
Referenced by DashBoard::delUser().
getEmployees()
std::set<Employee*, EmployeeNifCompare> UserDB::getEmployees () [inline]
Definition at line 92 of file UserDB.h.
{ return employees_; };
References employees_.
Referenced by Login::authenticate(), DashBoard::changePasswd(), DashBoard::delUser(), DashBoard::showAllUsers(), and DashBoard::showByPerm().
idExists()
bool UserDB::idExists (int id)
Checks if an employee with the given ID exists in the database.
Parameters
id The ID to check for.
Returns
True if an employee with the given ID exists, false otherwise.
Definition at line 5 of file UserDB.cpp.
                      {
  for (const auto& employee: this->employees_){
    if (employee->getId() == id) {
      return true;
    }
  }
  return false;
}
References employees_.
Referenced by DashBoard::addUser().
loadEmployees()
void UserDB::loadEmployees ()
Loads employees from a file.
Definition at line 24 of file UserDB.cpp.
                     {
  int nif, id, permission;
  std::time_t timestamp;
  std::ifstream ifs("UserDB.dat", std::ios::in | std::ios::binary);
  if (!ifs) {
    std::ofstream ofs("UserDB.dat", std::ios::out | std::ios::binary);
    if (!ofs) {
      throw std::runtime_error("Could not open UserDB.dat");
    }
    ofs.close();
  }
  
  while(true){
    Employee* employee = new Employee();
    if (!ifs.read(reinterpret_cast<char*>(&nif), sizeof(nif))) {
      delete employee;
      break;
    }
    if (!ifs.read(reinterpret_cast<char*>(&id), sizeof(id))) {
      delete employee;
      break;
    }
    if (!ifs.read(reinterpret_cast<char*>(&permission), sizeof(permission))) {
      delete employee;
      break;
    }
    if (!ifs.read(reinterpret_cast<char*>(&timestamp), sizeof(timestamp))) {
      delete employee;
      break;
    }
    employee->setNif(nif);
    employee->setId(id);
    employee->setPermission(permission);
    employee->setTimestamp(timestamp);
    employees_.insert(employee);
  }
  ifs.close();
}
References employees_, Employee::setId(), Employee::setNif(), Employee::setPermission(), and Employee::setTimestamp().
Referenced by UserDB().
nifExists()
bool UserDB::nifExists (int nif)
Checks if an employee with the given NIF exists in the database.
Parameters
nif The NIF to check for.
Returns
True if an employee with the given NIF exists, false otherwise.
Definition at line 15 of file UserDB.cpp.
                        {
  for (const auto& employee: this->employees_){
    if (employee->getNif() == nif) {
      return true;
    }
  }
  return false;
}
References employees_.
Referenced by DashBoard::addUser().
saveEmployees()
int UserDB::saveEmployees ()
Saves all employees to a file.
Returns
1 if employees were saved successfully, 0 otherwise.
Definition at line 107 of file UserDB.cpp.
                     {
  std::ofstream ofs("UserDB.dat", std::ios::out | std::ios::binary);
  if (!ofs) {
    return 0;
  }
  int id;
  int nif;
  std::time_t timestamp;
  int permission;
  for (const auto& employee : employees_) {
    nif = employee->getNif();
    id = employee->getId();
    timestamp = employee->getTimestamp();
    permission = employee->getPermission();
    ofs.write(reinterpret_cast<const char*>(&nif), sizeof(nif));
    ofs.write(reinterpret_cast<const char*>(&id), sizeof(id));
    ofs.write(reinterpret_cast<const char*>(&permission), sizeof(permission));
    ofs.write(reinterpret_cast<const char*>(&timestamp), sizeof(timestamp));
  }
  ofs.close();
  return 1;
}
References employees_.
showAll()
void UserDB::showAll ()
Displays information about all employees in the database.
Definition at line 79 of file UserDB.cpp.
               {
  std::cout << "Showing all users..." << std::endl;
  for (const auto& employee: employees_){
    employee->showinfo();
  }
}
References employees_.
showByPerm()
void UserDB::showByPerm (int permission)
Displays information about employees with a specific permission level.
Parameters
permission The permission level to filter employees by.
Definition at line 87 of file UserDB.cpp.
                               {
  std::cout << "Showing users by permision..." << std::endl;
  for (const auto& employee: employees_){
    if (employee->getPermission() == permision){
      employee->showinfo();
    }
  }
}
References employees_.
Member Data Documentation
employees_
std::set<Employee*, EmployeeNifCompare> UserDB::employees_ [private]
Set of employees stored in the database.
Definition at line 36 of file UserDB.h.
Referenced by addUser(), delUser(), getEmployees(), idExists(), loadEmployees(), nifExists(), saveEmployees(), showAll(), showByPerm(), and ~UserDB().
num_employees_
int UserDB::num_employees_ [private]
Number of employees in the database.
Definition at line 37 of file UserDB.h.
Referenced by addUser(), delUser(), and UserDB().
The documentation for this class was generated from the following files:
include/UserDB.h
src/UserDB.cpp