Employee Class Reference
Represents an Employee.
#include <Employee.h>
Public Member Functions
Employee (int nif=0, int id=0, int permission=0)
Constructor for the Employee class.
void showinfo ()
Displays information about the employee.
std::time_t getTimestamp ()
int getNif () const
int getId () const
int getPermission () const
void setNif (int nif)
void setId (int id)
std::string getEmployType ()
void setPermission (int permission)
void setTimestamp (std::time_t timestamp)
bool operator< (const Employee &right) const
Overloaded less-than operator to compare two employees.
Protected Attributes
int nif_
int id_
int permission_
std::time_t timestamp_
Detailed Description
Represents an Employee.
This class represents an Employee with attributes such as NIF, ID, permission level, and timestamp.
Definition at line 18 of file Employee.h.
Constructor & Destructor Documentation
Employee()
Employee::Employee (int nif = 0, int id = 0, int permission = 0)
Constructor for the Employee class.
Parameters
nif National Identification Number of the employee.
id Unique identifier of the employee.
permission Permission level of the employee.
Definition at line 4 of file Employee.cpp.
                                                 {
  this->nif_ = nif;
  this->id_ = id;
  this->permission_ = permission;
  this->timestamp_ = std::time(0);
}
References id_, nif_, permission_, and timestamp_.
Member Function Documentation
getEmployType()
std::string Employee::getEmployType ()
Definition at line 12 of file Employee.cpp.
                       {
  if (this->permission_ == 1)
    return "Worker";
  else if (this->permission_ == 2)
    return "Supervisor";
  else
    return "Admin";
}
References permission_.
Referenced by DashBoard::showMainMenu().
getId()
int Employee::getId () const
Definition at line 27 of file Employee.cpp.
                     {
  return id_;
}
References id_.
Referenced by DashBoard::changePasswd(), and EmployeeNifCompare::operator()().
getNif()
int Employee::getNif () const
Definition at line 22 of file Employee.cpp.
                      {
  return nif_;
}
References nif_.
Referenced by DashBoard::changePasswd(), and EmployeeNifCompare::operator()().
getPermission()
int Employee::getPermission () const
Definition at line 32 of file Employee.cpp.
                             {
  return permission_;
}
References permission_.
Referenced by operator<(), and DashBoard::showMainMenu().
getTimestamp()
std::time_t Employee::getTimestamp ()
Definition at line 37 of file Employee.cpp.
                      {
  return timestamp_;
}
References timestamp_.
operator<()
bool Employee::operator< (const Employee & right) const
Overloaded less-than operator to compare two employees.
Parameters
right The employee to compare with.
Returns
True if this employee is less than the other employee, false otherwise.
Definition at line 69 of file Employee.cpp.
                                               {
  return (this->permission_ < right.getPermission());
}
References getPermission(), and permission_.
setId()
void Employee::setId (int id)
Definition at line 47 of file Employee.cpp.
                     {
  id_ = id;
}
References id_.
Referenced by UserDB::loadEmployees().
setNif()
void Employee::setNif (int nif)
Definition at line 42 of file Employee.cpp.
                       {
  nif_ = nif;
}
References nif_.
Referenced by UserDB::loadEmployees().
setPermission()
void Employee::setPermission (int permission)
Definition at line 52 of file Employee.cpp.
                                     {
  permission_ = permission;
}
References permission_.
Referenced by UserDB::loadEmployees().
setTimestamp()
void Employee::setTimestamp (std::time_t timestamp)
Definition at line 57 of file Employee.cpp.
                                         {
  timestamp_ = timestamp;
}
References timestamp_.
Referenced by UserDB::loadEmployees().
showinfo()
void Employee::showinfo ()
Displays information about the employee.
Definition at line 62 of file Employee.cpp.
                  {
  std::cout << "NIF: " << nif_ << std::endl;
  std::cout << "ID: " << id_ << std::endl;
  std::cout << "permission: " << permission_ << std::endl;
  std::cout << "Timestamp: " << timestamp_ << std::endl;
}
References id_, nif_, permission_, and timestamp_.
Member Data Documentation
id_
int Employee::id_ [protected]
Unique identifier of the employee. Used as password in the login process.
Definition at line 21 of file Employee.h.
Referenced by Employee(), getId(), setId(), and showinfo().
nif_
int Employee::nif_ [protected]
National Identification Number of the employee.
Definition at line 20 of file Employee.h.
Referenced by Employee(), getNif(), setNif(), and showinfo().
permission_
int Employee::permission_ [protected]
Permission level of the employee (3 for admins, 2 for supervisors, 1 for workers).
Definition at line 22 of file Employee.h.
Referenced by Admin::Admin(), Employee(), getEmployType(), getPermission(), operator<(), setPermission(), showinfo(), Supervisor::Supervisor(), and Worker::Worker().
timestamp_
std::time_t Employee::timestamp_ [protected]
Timestamp indicating when the employee was created.
Definition at line 23 of file Employee.h.
Referenced by Employee(), getTimestamp(), setTimestamp(), and showinfo().
The documentation for this class was generated from the following files:
include/Employee.h
src/Employee.cpp