SensorDB Class Reference
Represents a database of sensors.
#include <SensorDB.h>
Public Member Functions
SensorDB ()
Constructor for the SensorDB class.
~SensorDB ()
Destructor for the SensorDB class.
Sensor * getSensByType (int type)
Retrieves the sensors of the specified type.
Sensor * getAsensor (int id)
Retrieves a sensor with the specified ID.
std::vector< Sensor * > getSensors ()
int getNumSens ()
Retrieves the number of sensors in the database.
int getNsensByType (int type)
Retrieves the number of sensors of the specified type in the database.
int getNextId ()
Retrieves the next available ID for a new sensor.
int save ()
Saves sensor information to a file.
void addSensor (int type, int id)
Adds a new sensor to the database.
void showAll ()
Displays information about all sensors in the database.
void showByType (int type)
Displays information about sensors of the specified type in the database.
void showOne (int id)
Displays information about the sensor with the specified ID.
void delSensor (int id)
Delete the sensor with the specified ID from the database.
Private Attributes
std::vector< Sensor * > sensors_
Detailed Description
Represents a database of sensors.
This class represents a database of sensors, with functionalities for adding, deleting, retrieving, and displaying sensor information.
Definition at line 29 of file SensorDB.h.
Constructor & Destructor Documentation
SensorDB()
SensorDB::SensorDB ()
Constructor for the SensorDB class.
Definition at line 35 of file SensorDB.cpp.
                   {
  std::string line, id, type;
  uint nline = 1;
  std::ifstream database("SensorDB.txt");
    
  if (!database.is_open()){
    std::cerr << "Error: Cannot open file SensorDB.txt" << std::endl;
    exit(1);
  }
  while (getline(database, line)) { // Lee línea por línea del archivo
    std::stringstream r_line(line);
    if (!getline(r_line, id, '-') || !getline(r_line, type)) {
      std::cerr << "Format error in file SensorDB.txt at line: " << nline << ". Skipping..." << std::endl;
      nline++;
      continue;
    }
    try{
      SensorDB::addSensor(stoi(type), stoi(id));
    }catch(std::exception &e){
      throw;
    }
    nline++;
  }
  database.close();
}
References addSensor().
 SensorDB()
SensorDB::~SensorDB ()
Destructor for the SensorDB class.
Definition at line 61 of file SensorDB.cpp.
                    {
  for (Sensor *sensor : this->sensors_) {
    delete sensor;
  }
  this->sensors_.clear();
}
References sensors_.
Member Function Documentation
addSensor()
void SensorDB::addSensor (int type, int id)
Adds a new sensor to the database.
Parameters
type Type of the sensor to add.
id ID of the sensor to add.
Definition at line 4 of file SensorDB.cpp.
                                   {
  Sensor *sensorptr;
  switch(type) {
  case TYPE_TEMP:
    sensorptr = new Temp(id, type);
    break;
  case TYPE_HUM:
    sensorptr = new Humidity(id, type);
    break;
  case TYPE_LIGHT:
    sensorptr = new LightQuality(id, type);
    break;
  case TYPE_AIR:
    sensorptr = new AirQuality(id, type);
    break;
  case TYPE_MAG:
    sensorptr = new Magnetic(id, type);
    break;
  case TYPE_CAM:
    sensorptr = new Camera(id, type);
    break;
  case TYPE_RGB:
    sensorptr = new Rgb(id, type);
    break;
  default:
    sensorptr = new Termic(id, type);
  }
  this->sensors_.push_back(sensorptr);
}
References sensors_, TYPE_AIR, TYPE_CAM, TYPE_HUM, TYPE_LIGHT, TYPE_MAG, TYPE_RGB, and TYPE_TEMP.
Referenced by DashBoard::addSensor(), and SensorDB().
delSensor()
void SensorDB::delSensor (int id)
Delete the sensor with the specified ID from the database.
Parameters
id ID of the sensor to delete.
Definition at line 179 of file SensorDB.cpp.
                         {
  int i, pos = -1;
  for(i = 0; i < SensorDB::getNumSens(); i++){
    if(this->sensors_[i]->getId() == id){
      pos = i;
      break;
    }
  }
  if(pos!= -1){
    delete this->sensors_[pos];
    this->sensors_.erase(this->sensors_.begin() + pos);
  }else{
    std::cout << "Sensor not found.\n";
  }
}
References getNumSens(), and sensors_.
Referenced by DashBoard::delSensor().
getAsensor()
Sensor * SensorDB::getAsensor (int id)
Retrieves a sensor with the specified ID.
Parameters
id ID of the sensor to retrieve.
Returns
Pointer to the sensor with the specified ID, or nullptr if not found.
Definition at line 107 of file SensorDB.cpp.
                          {
  int i;
  for(i = 0; i < SensorDB::getNumSens(); i++){
    if(this->sensors_[i]->getId() == id){
      return this->sensors_[i];
    }
  }
  return nullptr;
}
References getNumSens(), and sensors_.
Referenced by DashBoard::delSensor(), and showOne().
getNextId()
int SensorDB::getNextId ()
Retrieves the next available ID for a new sensor.
Returns
Next available ID for a new sensor.
Definition at line 139 of file SensorDB.cpp.
                   {
  int i, id = 1;
  for(i = 0; i < SensorDB::getNumSens(); i++){
    if(this->sensors_[i]->getId() > id){
      id = this->sensors_[i]->getId();
    }
  }
  return id + 1;
}
References getNumSens(), and sensors_.
Referenced by DashBoard::addSensor().
getNsensByType()
int SensorDB::getNsensByType (int type)
Retrieves the number of sensors of the specified type in the database.
Parameters
type Type of sensors to count.
Returns
Number of sensors of the specified type in the database.
Definition at line 119 of file SensorDB.cpp.
                                {
  int i, nsens = 0;
  for(i = 0; i < SensorDB::getNumSens(); i++){
    if(this->sensors_[i]->getType() == type){
      nsens++;
    }
  }
  return nsens;
}
References getNumSens(), and sensors_.
Referenced by getSensByType().
getNumSens()
int SensorDB::getNumSens ()
Retrieves the number of sensors in the database.
Returns
Number of sensors in the database.
Definition at line 91 of file SensorDB.cpp.
                    {
  return this->sensors_[0]->getNsensors();
}
References sensors_.
Referenced by delSensor(), getAsensor(), getNextId(), getNsensByType(), Alarm::readMagSens(), save(), showAll(), and showByType().
getSensByType()
Sensor * SensorDB::getSensByType (int type)
Retrieves the sensors of the specified type.
Parameters
type Type of the sensor to retrieve.
Returns
Pointer to the first sensor of the specified type, or nullptr if not found. It allocate memory dinamically.
Definition at line 69 of file SensorDB.cpp.
                               {
  int i, j, nsens;
  Sensor* senslist;
  nsens = SensorDB::getNsensByType(type);
  senslist = new Sensor[nsens]; // allocating memory for that number
  j = 0;
  for(i = 0; i < (int)this->sensors_.size(); i++){ // getting sens of that type
    if(this->sensors_[i]->getType() == type){
      senslist[j] = *this->sensors_[i];
      j++;
    }
  }
  return senslist;
}
References getNsensByType(), and sensors_.
getSensors()
std::vector< Sensor * > SensorDB::getSensors ()
Definition at line 86 of file SensorDB.cpp.
                    {
  return this->sensors_;
}
References sensors_.
Referenced by DashBoard::delSensor(), Alarm::readMagSens(), DashBoard::showAllSensors(), and DashBoard::showByType().
save()
int SensorDB::save ()
Saves sensor information to a file.
Returns
0 if successful, -1 otherwise.
Definition at line 152 of file SensorDB.cpp.
              {
  int i;
  std::ofstream database("SensorDB.txt", std::ofstream::out | std::ofstream::trunc);
    // Verificar si el archivo se abrió correctamente
  if (!database) {
    std::cerr << "File 'SensorDB.txt' Not Found." << std::endl;
    return 0;
  }
  for (i = 0; i < SensorDB::getNumSens(); i++) {
    database << this->sensors_[i]->getId() << "-" << this->sensors_[i]->getType() << std::endl;
  }
  database.close();
  return 1;
}
References getNumSens(), and sensors_.
showAll()
void SensorDB::showAll ()
Displays information about all sensors in the database.
Definition at line 130 of file SensorDB.cpp.
                 {
  int i;
  for(i = 0; i < SensorDB::getNumSens(); i++){
    this->sensors_[i]->showInfo();
  }
}
References getNumSens(), and sensors_.
Referenced by DashBoard::showAllSensors().
showByType()
void SensorDB::showByType (int type)
Displays information about sensors of the specified type in the database.
Parameters
type Type of sensors to display.
Definition at line 96 of file SensorDB.cpp.
                            {
  int i;
  for(i = 0; i < SensorDB::getNumSens(); i++){
    if(sensors_[i]->getType() == type){
      sensors_[i]->showInfo();
    }
  }
}
References getNumSens(), and sensors_.
Referenced by DashBoard::showByType().
showOne()
void SensorDB::showOne (int id)
Displays information about the sensor with the specified ID.
Parameters
id ID of the sensor to display.
Definition at line 169 of file SensorDB.cpp.
                       {
  Sensor *sens = this->getAsensor(id);
  if (sens == nullptr)
    std::cout << "Sensor not found.\n";
  else
    sens->showInfo();
}
References getAsensor(), and Sensor::showInfo().
Member Data Documentation
sensors_
std::vector<Sensor*> SensorDB::sensors_ [private]
Vector to store pointers to Sensor objects.
Definition at line 31 of file SensorDB.h.
Referenced by addSensor(), delSensor(), getAsensor(), getNextId(), getNsensByType(), getNumSens(), getSensByType(), getSensors(), save(), showAll(), showByType(), and ~SensorDB().
The documentation for this class was generated from the following files:
include/SensorDB.h
src/SensorDB.cpp