DashBoard Class Reference
Represents a dashboard for system management.
#include <DashBoard.h>
Public Member Functions
DashBoard (Employee *user=nullptr, SensorDB *sensorDB=nullptr, Alarm *alarm=nullptr, UserDB *userDB=nullptr)
Constructor for the DashBoard class.
~DashBoard ()
Destructor for the DashBoard class.
void showMainMenu ()
Displays the main menu.
void showSensorsMenu ()
Displays the sensors menu.
void showAllSensors (SensorDB *sensorDB)
Displays information about all sensors.
void showByType (SensorDB *sensorDB)
Displays information about sensors of a specific type.
void addSensor (SensorDB *sensorDB)
Adds a new sensor to the database.
int selectTypeSensor ()
Prompts the user to select a sensor type.
void showAlarmMenu (Alarm alarm)
Displays the alarm menu.
void changePasswd (UserDB *userDB, Employee *user)
Changes the password of a user.
void showByPerm (UserDB *userDB)
Displays information about users by permission level.
void delUser (UserDB *userDB)
Deletes a user from the database.
void showAllUsers (UserDB *userDB)
Displays information about all users.
void addUser (UserDB *userDB)
Adds a new user to the database.
void showUsersMenu ()
Displays the users menu.
int askForOption (int max)
Prompts the user to select an option.
void delSensor (SensorDB *sensorDB)
Deletes a sensor from the database.
void showAlarmSts (Alarm *alarm, SensorDB *sensorDB)
Displays the status of the alarm.
void onOffAlarm (Alarm *alarm)
Turns the alarm on or off.
int getOption ()
Employee * getUser ()
void setUser (Employee *user)
Private Attributes
Employee * user_
int option_
SensorDB * sensorDB_
Alarm * alarm_
UserDB * userDB_
Detailed Description
Represents a dashboard for system management.
This class represents a dashboard for system management, with functionalities for displaying menus and managing sensors.
Definition at line 23 of file DashBoard.h.
Constructor & Destructor Documentation
DashBoard()
DashBoard::DashBoard (Employee * user = nullptr, SensorDB * sensorDB = nullptr, Alarm * alarm = nullptr, UserDB * userDB = nullptr)
Constructor for the DashBoard class.
Parameters
user Pointer to the logged-in user.
sensorDB Pointer to the SensorDB object.
alarm Pointer to the Alarm object.
userDB Pointer to the UserDB object.
Definition at line 3 of file DashBoard.cpp.
                                                                                     {
  this->user_ = user;
  this->option_ = 0;
  this->sensorDB_ = sensorDB;
  this->alarm_ = alarm;
  this->userDB_ = userDB;
}
References alarm_, option_, sensorDB_, user_, and userDB_.
 DashBoard()
DashBoard::~DashBoard ()
Destructor for the DashBoard class.
Definition at line 11 of file DashBoard.cpp.
                      {
  delete this->sensorDB_;
}
References sensorDB_.
Member Function Documentation
addSensor()
void DashBoard::addSensor (SensorDB * sensorDB)
Adds a new sensor to the database.
Parameters
sensorDB Pointer to the SensorDB object.
Definition at line 324 of file DashBoard.cpp.
                                      {
  int type, id;
  std::cout << "Select type to add:\n";
  type = DashBoard::selectTypeSensor();
  id = sensordb->getNextId();
  sensordb->addSensor(type, id);
}
References SensorDB::addSensor(), SensorDB::getNextId(), and selectTypeSensor().
addUser()
void DashBoard::addUser (UserDB * userDB)
Adds a new user to the database.
Parameters
userDB Pointer to the UserDB object.
Definition at line 203 of file DashBoard.cpp.
                                {
  int nif;
  int password;
  int permission;
  bool valid = false;
  Employee *newuser;
  while(!valid){
    std::cout << "Insert NIF: ";
    try{
      nif = DashBoard::askForOption(99999999);
      if(userDB->nifExists(nif)){
        std::cout << "NIF already exists, try again: ";
      }else{
        valid = true;
      }
    }catch(ValueError &e){
      std::cout << "\nInvalid number, try again\n\n";
    }
  }
  valid = false;
  while(!valid){
    std::cout << "Insert password: ";
    try{
      password = DashBoard::askForOption(99999);
      if(userDB->idExists(password)){
        std::cout << "Invalid password, try again: ";
      }else{
        valid = true;
      }
    }catch(ValueError &e){
      std::cout << "\nInvalid number, try again\n\n";
    }
  }
  valid = false;
  while(!valid){
    std::cout << "Insert permission(1 for worker, 2 for supervisor, 3 for admin): ";
    try{
      permission = DashBoard::askForOption(3);
      valid = true;
    }catch(ValueError &e){
      std::cout << "\nInvalid number, try again\n\n";
    }
  }
  newuser = new Employee(nif, password, permission);
  userDB->addUser(newuser);
}
References UserDB::addUser(), askForOption(), UserDB::idExists(), and UserDB::nifExists().
askForOption()
int DashBoard::askForOption (int max)
Prompts the user to select an option.
Parameters
max Maximum allowed option (between 1 and max).
Returns
Selected option.
Definition at line 29 of file DashBoard.cpp.
                               {
  int option;
  std::cin >> option;
  if (option < 1 || option > max){
    if (std::cin.fail()) {
      // Limpiamos el estado de error de std::cin
      std::cin.clear();
      // Descartamos cualquier entrada incorrecta en el búfer
      std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    }
    throw ValueError();
  }
  std::cout << std::endl;
  std::cout << "Selected option: " << option << std::endl << std::endl;
  return option;
}
Referenced by addUser(), changePasswd(), delSensor(), delUser(), selectTypeSensor(), showAlarmMenu(), showByPerm(), showMainMenu(), showSensorsMenu(), and showUsersMenu().
changePasswd()
void DashBoard::changePasswd (UserDB * userDB, Employee * user)
Changes the password of a user.
Parameters
userDB Pointer to the UserDB object.
user Pointer to the Employee object representing the user.
Definition at line 114 of file DashBoard.cpp.
                                                      {
  bool valid = false;
  int oldpasswd, newpasswd;
  while(!valid){
    std::cout << "Enter your current password: ";
    try{
      oldpasswd = DashBoard::askForOption(99999);
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again\n\n";
      continue;
    }
    if(user->getId() == oldpasswd){
      valid = true;
    }else{
      std::cerr << "\nInvalid number, try again\n\n";
    }
  }
  valid = false;
  while(!valid){
    std::cout << "Enter your new password: ";
    try{
      newpasswd = DashBoard::askForOption(99999);
      valid = true;
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again\n\n";
    }
  }
  for(auto const& employee: userDB->getEmployees()){
    if (employee->getNif() == user->getNif()){
      employee->setId(newpasswd);
      break;
    }
  }
  std::cout << "Password changed successfully.\n" << std::endl;
}
References askForOption(), UserDB::getEmployees(), Employee::getId(), and Employee::getNif().
delSensor()
void DashBoard::delSensor (SensorDB * sensorDB)
Deletes a sensor from the database.
Parameters
sensorDB Pointer to the SensorDB object.
Definition at line 334 of file DashBoard.cpp.
                                      {
  int id, i, maxid = 0;
  bool valid = false;
  std::cout << "Select sensor to delete(the id):\n";
  for(i = 0; i < (int)sensorDB->getSensors().size(); i++){
    if(maxid < sensorDB->getSensors()[i]->getId()){
      maxid = sensorDB->getSensors()[i]->getId();
    }
    std::cout << "Id: " << sensorDB->getSensors()[i]->getId() << " - ";
    switch(sensorDB->getSensors()[i]->getType()){
    case(TYPE_TEMP):
      std::cout << "Temperature.\n";
      break;
    case(TYPE_HUM):
      std::cout << "Humidity.\n";
      break;
    case(TYPE_MAG):
      std::cout << "Magnetic.\n";
      break;
    case(TYPE_LIGHT):
      std::cout << "Light.\n";
      break;
    case(TYPE_AIR):
      std::cout << "Air quality.\n";
      break;
    case(TYPE_TERMIC):
      std::cout << "Termic Camera.\n";
      break;
    case(TYPE_RGB):
      std::cout << "RGB Camera.\n";
      break;
    case(TYPE_CAM):
      std::cout << "Camera.\n";
      break;
    }
  }
  while(!valid){
    std::cout << "Your option: ";
    try{
      id = DashBoard::askForOption(maxid);
      if(sensorDB->getAsensor(id) == nullptr){
        throw ValueError();
      }
      valid = true;
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again(1 - " << maxid << ")\n\n";
    }
  }
  sensorDB->delSensor(id);
  std::cout << "\nSensor deleted.\n" << std::endl;
}
References askForOption(), SensorDB::delSensor(), SensorDB::getAsensor(), SensorDB::getSensors(), TYPE_AIR, TYPE_CAM, TYPE_HUM, TYPE_LIGHT, TYPE_MAG, TYPE_RGB, TYPE_TEMP, and TYPE_TERMIC.
delUser()
void DashBoard::delUser (UserDB * userDB)
Deletes a user from the database.
Parameters
userDB Pointer to the UserDB object.
Definition at line 48 of file DashBoard.cpp.
                                 {
  bool valid = false;
  int i, nif;
  while(!valid){
    i = 1;
    std::cout << "NIFs to delete:\n";
    for (auto const& employee: userDB->getEmployees()) {
      std::cout << i << ". " << employee->getNif() << std::endl;
      i++;
    }
    try{
      std::cout << "Select the NIF of the user to delete: ";
      nif = DashBoard::askForOption(i - 1);
      valid = true;
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again(1 - " << i - 1 << ")\n\n";
    }
  }
  userDB->delUser(nif - 1);
}
References askForOption(), UserDB::delUser(), and UserDB::getEmployees().
getOption()
int DashBoard::getOption ()
Definition at line 402 of file DashBoard.cpp.
                     {
  return this->option_;
}
References option_.
getUser()
Employee * DashBoard::getUser ()
Definition at line 407 of file DashBoard.cpp.
                   {
  return this->user_;
}
References user_.
onOffAlarm()
void DashBoard::onOffAlarm (Alarm * alarm)
Turns the alarm on or off.
Parameters
alarm Pointer to the Alarm object.
Definition at line 252 of file DashBoard.cpp.
                                 {
  alarm->setOnOff(!alarm->getOnOff());
  std::cout << "Alarm turned " << (alarm->getOnOff()? "on.\n" : "off.\n") << std::endl;
}
References Alarm::getOnOff(), and Alarm::setOnOff().
selectTypeSensor()
int DashBoard::selectTypeSensor ()
Prompts the user to select a sensor type.
Returns
Selected sensor type.
Definition at line 300 of file DashBoard.cpp.
                           {
  bool numvalid = false;
  int type;
  while(!numvalid){
    std::cout << "Types:\n";
    std::cout << "1. Temperature.\n";
    std::cout << "2. Humidity.\n";
    std::cout << "3. Light quality.\n";
    std::cout << "4. Air Quality.\n";
    std::cout << "5. Camera RGB.\n";
    std::cout << "6. Camera Termic.\n";
    std::cout << "Your option: ";
    try{
      type = DashBoard::askForOption(6);
      numvalid = true;
    }catch (ValueError &e){
      std::cerr << "\nInvalid number, try again(1 - 6)\n\n";
    }
  }
  return type;
}
References askForOption().
Referenced by addSensor(), and showByType().
setUser()
void DashBoard::setUser (Employee * user)
Definition at line 24 of file DashBoard.cpp.
                                 {
  this->user_ = user;
}
References user_.
showAlarmMenu()
void DashBoard::showAlarmMenu (Alarm alarm)
Displays the alarm menu.
Parameters
alarm Reference to the Alarm object.
Definition at line 263 of file DashBoard.cpp.
                                   {
  bool valid = false;
  while(!valid){
    std::cout << "Manage Alarm." << std::endl;
    if(alarm.getOnOff()){
    std::cout << "1. Turn off Alarm." << std::endl;
    }else{
        std::cout << "1. Turn on Alarm." << std::endl;
    }
    std::cout << "2. Show status." << std::endl;
    std::cout << "3. Go back." << std::endl;
    std::cout << "Your option: ";
    try{
      this->option_ = DashBoard::askForOption(3);
      valid = true;
    }catch(ValueError &e){
      std::cout << "\nInvalid number, try again(1 - 2)\n\n";
    }
  }
}
References askForOption(), Alarm::getOnOff(), and option_.
showAlarmSts()
void DashBoard::showAlarmSts (Alarm * alarm, SensorDB * sensorDB)
Displays the status of the alarm.
Parameters
alarm Pointer to the Alarm object.
sensorDB Pointer to the SensorDB object.
Definition at line 258 of file DashBoard.cpp.
                                                       {
  alarm->showInfo(sensorDB);
}
References Alarm::showInfo().
showAllSensors()
void DashBoard::showAllSensors (SensorDB * sensorDB)
Displays information about all sensors.
Parameters
sensorDB Pointer to the SensorDB object.
Definition at line 286 of file DashBoard.cpp.
                                           {
  int i;
  for(i = 0; i < (int)sensorDB->getSensors().size(); i++){
    if (sensorDB->getSensors()[i]->getType() < TYPE_RGB){
      sensorDB->getSensors()[i]->scan(0.0, 100.0);
    }
  }
  std::cout << "\nSensors: " << std::endl;
  sensorDB->showAll();
  std::cout << std::endl;
}
References SensorDB::getSensors(), SensorDB::showAll(), and TYPE_RGB.
showAllUsers()
void DashBoard::showAllUsers (UserDB * userDB)
Displays information about all users.
Parameters
userDB Pointer to the UserDB object.
Definition at line 15 of file DashBoard.cpp.
                                           {
  std::cout << "All users:" << std::endl;
  for (auto const& employee: userDB->getEmployees()) {
    employee->showinfo();
  }
  std::cout << std::endl;
}
References UserDB::getEmployees().
showByPerm()
void DashBoard::showByPerm (UserDB * userDB)
Displays information about users by permission level.
Parameters
userDB Pointer to the UserDB object.
Definition at line 71 of file DashBoard.cpp.
                                    {
  bool valid = false;
  int permission;
  while(!valid){
    std::cout << "Enter the permission level: ";
    try{
      permission = DashBoard::askForOption(3);
      valid = true;
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again(1 - 3)\n\n";
    }
  }
  for (auto const& employee: userDB->getEmployees()) {
    if (employee->getPermission() == permission){
      employee->showinfo();
    }
  }
  std::cout << std::endl;
}
References askForOption(), and UserDB::getEmployees().
showByType()
void DashBoard::showByType (SensorDB * sensorDB)
Displays information about sensors of a specific type.
Parameters
sensorDB Pointer to the SensorDB object.
Definition at line 388 of file DashBoard.cpp.
                                       {
  int type, i;
  type = DashBoard::selectTypeSensor();
  for(i = 0; i < (int)sensorDB->getSensors().size(); i++){
    if (sensorDB->getSensors()[i]->getType() == type){
      sensorDB->getSensors()[i]->scan(0.0, 100.0);
      }
  }
  std::cout << "\nSensors of type " << type << ": " << std::endl;
  sensorDB->showByType(type);
  std::cout << std::endl;
}
References SensorDB::getSensors(), selectTypeSensor(), and SensorDB::showByType().
showMainMenu()
void DashBoard::showMainMenu ()
Displays the main menu.
Definition at line 152 of file DashBoard.cpp.
                       {
  bool numvalid = false;
  int max = 4;
  std::cout << "Welcome to the DashBoard. Logged as: " << user_->getEmployType() << std::endl;
  while(!numvalid){
    std::cout << "What would you like to do?" << std::endl;
    std::cout << "1. Manage Sensors." << std::endl;
    std::cout << "2. Change my password." << std::endl;
    std::cout << "3. Log out." << std::endl;
    std::cout << "4. Exit." << std::endl;
    if (this->user_->getPermission() >= 2){
      std::cout << "5. Manage Alarm." << std::endl;
      max = 5;
    }
    if (this->user_->getPermission() >= 3){
      std::cout << "6. Manage Users." << std::endl;
      max = 6;
    }
    std::cout << "Your option: ";
    try{
      this->option_ = DashBoard::askForOption(max);
      numvalid = true;
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again(1 - " << max << ")\n\n";
    }
  }
}
References askForOption(), Employee::getEmployType(), Employee::getPermission(), option_, and user_.
showSensorsMenu()
void DashBoard::showSensorsMenu ()
Displays the sensors menu.
Definition at line 182 of file DashBoard.cpp.
                          {
  bool numvalid = false;
  while(!numvalid){
    std::cout << "Manage Sensors." << std::endl;
    std::cout << "1. Add a sensor." << std::endl;
    std::cout << "2. Show all sensors." << std::endl;
    std::cout << "3. Show sensors by type." << std::endl;
    std::cout << "4. Delete a sensor." << std::endl;
    std::cout << "5. Save and go back." << std::endl;
    std::cout << "Your option: ";
    try{
      this->option_ = DashBoard::askForOption(5);
      numvalid = true;
    }catch (ValueError &e){
      std::cout << "\nInvalid number, try again(1 - 5)\n\n";
    }
  }
}
References askForOption(), and option_.
showUsersMenu()
void DashBoard::showUsersMenu ()
Displays the users menu.
Definition at line 93 of file DashBoard.cpp.
                        {
  bool numvalid = false;
  int max = 5;
  std::cout << "What would you like to do?" << std::endl;
  while(!numvalid){
    std::cout << "1. Add user." << std::endl;
    std::cout << "2. Show all users." << std::endl;
    std::cout << "3. Show users by permission." << std::endl;
    std::cout << "4. Delete user." << std::endl;
    std::cout << "5. Save and Back." << std::endl;
    std::cout << "Your option: ";
    try{
      this->option_ = DashBoard::askForOption(max);
      numvalid = true;
    }catch(ValueError &e){
      std::cerr << "\nInvalid number, try again(1 - " << max << ")\n\n";
    }
  }
}
References askForOption(), and option_.
Member Data Documentation
alarm_
Alarm* DashBoard::alarm_ [private]
Pointer to the Alarm object.
Definition at line 28 of file DashBoard.h.
Referenced by DashBoard().
option_
int DashBoard::option_ [private]
Selected option in the menu.
Definition at line 26 of file DashBoard.h.
Referenced by DashBoard(), getOption(), showAlarmMenu(), showMainMenu(), showSensorsMenu(), and showUsersMenu().
sensorDB_
SensorDB* DashBoard::sensorDB_ [private]
Pointer to the SensorDB object.
Definition at line 27 of file DashBoard.h.
Referenced by DashBoard(), and ~DashBoard().
user_
Employee* DashBoard::user_ [private]
Pointer to the logged-in user.
Definition at line 25 of file DashBoard.h.
Referenced by DashBoard(), getUser(), setUser(), and showMainMenu().
userDB_
UserDB* DashBoard::userDB_ [private]
Pointer to the UserDB object.
Definition at line 29 of file DashBoard.h.
Referenced by DashBoard().
The documentation for this class was generated from the following files:
include/DashBoard.h
src/DashBoard.cpp