Alarm Class Reference
Represents an Alarm system.
#include <Alarm.h>
Public Member Functions
Alarm (bool onoff=false, bool intrusion=false)
Constructor for the Alarm class.
void setOnOff (bool onoff)
void setIntrusion (bool intrusion)
bool getOnOff ()
bool getIntrusion ()
void showInfo (SensorDB *sensDB)
Displays information about the alarm like if it is turned on or off, and if an intrusion has been detected.
bool readMagSens (SensorDB *sensDB)
Reads magnetic sensors to detect intrusions.
void callPolice (SensorDB *sensDB)
Calls the police if an intrusion is detected.
Private Attributes
bool onoff_
bool intrusion_
Detailed Description
Represents an Alarm system.
This class represents an alarm system with functionalities such as turning on/off the alarm, detecting intrusions, reading magnetic sensors, and calling the police if necessary.
Definition at line 18 of file Alarm.h.
Constructor & Destructor Documentation
Alarm()
Alarm::Alarm (bool onoff = false, bool intrusion = false)
Constructor for the Alarm class.
Parameters
onoff Initial state of the alarm (true for on, false for off).
intrusion Initial state of the intrusion detection (true if intrusion detected, false otherwise).
Definition at line 3 of file Alarm.cpp.
                                       {
    this->onoff_ = onoff;
    this->intrusion_ = intrusion;
}
References intrusion_, and onoff_.
Member Function Documentation
callPolice()
void Alarm::callPolice (SensorDB * sensDB)
Calls the police if an intrusion is detected.
Parameters
sensDB Pointer to the SensorDB object containing information about sensors.
Definition at line 51 of file Alarm.cpp.
                                  {
  this->intrusion_ = readMagSens(sensDB);
  if(this->intrusion_){
    std::cout << "Police called!" << std::endl;
  }else{
    std::cout << "Police not called!" << std::endl;
  }
}
References intrusion_, and readMagSens().
Referenced by showInfo().
getIntrusion()
bool Alarm::getIntrusion ()
Definition at line 19 of file Alarm.cpp.
                    {
    return this->intrusion_;
}
References intrusion_.
getOnOff()
bool Alarm::getOnOff ()
Definition at line 24 of file Alarm.cpp.
                {
    return this->onoff_;
}
References onoff_.
Referenced by DashBoard::onOffAlarm(), and DashBoard::showAlarmMenu().
readMagSens()
bool Alarm::readMagSens (SensorDB * sensDB)
Reads magnetic sensors to detect intrusions.
Parameters
sensDB Pointer to the SensorDB object containing information about sensors.
Returns
True if an intrusion is detected, false otherwise.
Definition at line 36 of file Alarm.cpp.
                                   {
  int i, nsens;
  nsens = sensDB->getNumSens();
  for(i = 0; i < nsens; i++){
    if(sensDB->getSensors()[i]->getType() == TYPE_MAG){
      if(sensDB->getSensors()[i]->getCurrent()[0] < 1.0){
        this->intrusion_ = true;
      }
    }
  }
  return this->intrusion_;
}
References SensorDB::getNumSens(), SensorDB::getSensors(), intrusion_, and TYPE_MAG.
Referenced by callPolice().
setIntrusion()
void Alarm::setIntrusion (bool intrusion)
Definition at line 9 of file Alarm.cpp.
                                  {
    this->intrusion_ = intrusion;
}
References intrusion_.
setOnOff()
void Alarm::setOnOff (bool onoff)
Definition at line 14 of file Alarm.cpp.
                          {
    this->onoff_ = onoff;
}
References onoff_.
Referenced by DashBoard::onOffAlarm().
showInfo()
void Alarm::showInfo (SensorDB * sensDB)
Displays information about the alarm like if it is turned on or off, and if an intrusion has been detected.
Parameters
sensDB Pointer to the SensorDB object containing information about sensors(it will check the magnetic sensors).
Definition at line 29 of file Alarm.cpp.
                                {
  Alarm::callPolice(sensDB);
  std::cout << "Alarm status: " << (this->onoff_? "ON" : "OFF") << std::endl;
  std::cout << "Intrusion hapened? " << (this->intrusion_? "YES" : "NO") << std::endl;
}
References callPolice(), intrusion_, and onoff_.
Referenced by DashBoard::showAlarmSts().
Member Data Documentation
intrusion_
bool Alarm::intrusion_ [private]
Indicates whether an intrusion has been detected.
Definition at line 21 of file Alarm.h.
Referenced by Alarm(), callPolice(), getIntrusion(), readMagSens(), setIntrusion(), and showInfo().
onoff_
bool Alarm::onoff_ [private]
Indicates whether the alarm is turned on or off.
Definition at line 20 of file Alarm.h.
Referenced by Alarm(), getOnOff(), setOnOff(), and showInfo().
The documentation for this class was generated from the following files:
include/Alarm.h
src/Alarm.cpp